### ISSUE TITLE
Not showing new version in plugin update manager

### ISSUE THREAD

**Issue by ghost** [borisbu/OctoRelay#14]
I can see the new version 1.1.0 available in this github, but it is not appearing in the software update manager in octoprint.

![Screenshot_20210403_212610](https://user-images.githubusercontent.com/5692416/113496834-44e00e00-94c3-11eb-86bb-fdc8fdd3d733.png)

Maybe missing some data as in https://docs.octoprint.org/en/master/bundledplugins/softwareupdate.html#octoprint-plugin-softwareupdate-check-config

**Comment by mauricio-camayo** [comment]
Had to uninstall and install again in order to get the new version
![Screen Shot 2021-04-04 at 20 58 17](https://user-images.githubusercontent.com/5692416/113529220-87b7e980-9588-11eb-9461-6d2dffce4c80.png)
Still missing the "Release Channel" and "Available" version information

**Comment by mauricio-camayo** [comment]
I've seen that this repo does not have releases yet https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository 
Maybe it is all that is needed

**Comment by RobinTail** [comment]
This issue seems to be fixed at the moment.
In case it's not, please open a new issue or let me know in a comment. 

![2023-07-02_23-19-47](https://github.com/borisbu/OctoRelay/assets/13189514/2e4fd92b-8c46-4f61-87a9-067b56642603)
