### ISSUE TITLE
Feature: disconnect before turning printer relay OFF

### ISSUE THREAD

**Issue by RobinTail** [borisbu/OctoRelay#153]
> In a same way autodisconnect would be great. Disconnect printer before relay is deactivated would avoid "SerialException" error from octoprint.

This would require for OctoRelay to know which relay controls the printer.

_Originally posted by @RobinTail in https://github.com/borisbu/OctoRelay/issues/18#issuecomment-1664642386_

**Comment by Ano10** [comment]
Could this be simply a check box next to "OFF after printing" like "Disconnect printer before OFF" ?

**Comment by Ano10** [comment]
Well I've having only one printer connected to my raspberry pi running octoprint, so I haven't considere case where there would be many printer connected to one raspberry pi. Can it even be possible ? 😅 I though octoprint could only control one printer.

**Comment by RobinTail** [comment]
I found a way to disconnect the printer before turning its relay off, @Ano10 .
Works like a charm — no error messages, even in the middle of ongoing printing process.
#207
