### ISSUE TITLE
Any way to access the relay state through api?

### ISSUE THREAD

**Issue by Deymos42** [borisbu/OctoRelay#17]
Hi,

I am looking for the way to get the status of relay sending http request to  octorelay on octoprint server. It's possible?

Thanks in advance.

**Comment by jneilliii** [comment]
There appears to be a `listAllStatus` API command added with https://github.com/borisbu/OctoRelay/pull/38.

```
POST /api/plugin/octorelay HTTP/1.1
Host: octopi.local
Content-Type: application/json
X-Api-Key: <your API key>

{
  "command": "listAllStatus"
}
```

Looks like there is a `getStatus` command as well, that appears to need a `pin` parameter, which I think matches up with r1, r2, r3, etc...

```
POST /api/plugin/octorelay HTTP/1.1
Host: octopi.local
Content-Type: application/json
X-Api-Key: <your API key>

{
  "command": "getStatus",
  "pin": "r1"
}
```

**Comment by RobinTail** [comment]
[the correct answer](https://github.com/borisbu/OctoRelay/issues/17#issuecomment-986106899) given
