### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by Targa2405** [borisbu/OctoRelay#195]
I'm unable to update from version 2.2.2 to the latest version, each time I get the same error-message;

"WARNING: Built wheel for OctoRelay is invalid: Metadata 1.2 mandates PEP 440 version, but 'unknown-g1f04e4f3' is not
ERROR: Could not build wheels for OctoRelay, which is required to install pyproject.toml-based projects"

**Comment by RobinTail** [comment]
Sorry for the inconvenience, @Targa2405 .

1. Please proceed to the OctoRelay settings
2. Go to Plugin Manager
3. Click on Get More button
4. Scroll the window down to `... from URL` section
5. Copy/paste the following URL:

```
https://github.com/borisbu/OctoRelay/releases/latest/download/release.zip
```

6. And click on the Install button next to it.

This should solve the issue for you.

<img width="561" alt="Screenshot 2023-08-24 at 23 42 32" src="https://github.com/borisbu/OctoRelay/assets/13189514/ce047e00-2788-4db9-9b74-f4b3f2688109">

**Comment by ak185158** [comment]
This worked to resolve the error for me as I was having the same issue with this release.

**Comment by RobinTail** [comment]
Thank you for letting me know, @ak185158 .
There will be another bugfix today — #197 
I hope this time you'll be able to update automatically.
If not, please open another issue.
