### ISSUE TITLE
Switch off delay

### ISSUE THREAD

**Issue by mirkokrajco** [borisbu/OctoRelay#24]
Hello, time delay for switch off not working ???

**Comment by borisbu** [comment]
Works for me, do you have more information? The delay is not for manual switchoff, only after print finished

**Comment by mirkokrajco** [comment]
Hello,

When printing is complete, the printer will turn off immediately and not
wait for a delay.

[image: Bez názvu.png]

This is my setting. The printer should wait 180 seconds, but it does not
wait.What is wrong ???
Best regards
Miroslav



so 1. 5. 2021 o 17:05 borisbu ***@***.***> napísal(a):
