### ISSUE TITLE
Feature: auto OFF not related to printing

### ISSUE THREAD

**Issue by Katapippo** [borisbu/OctoRelay#27]
Thank you
Great plugin
Is it possible to add the timed shutdown function without starting prints?
It would be very convenient for me to manage the buttons of the Sunlu Dryer Box S1, it starts up via relay but then you have to give 1 click to make it turn on and bring it to temperature, so if I had the possibility to give 1-3 seconds to the relay I could connect it to the button physical to start it remotely.
Did I have a piece of code to add?

Thank you

**Comment by RobinTail** [comment]
The feature released in v3.8.0 🚀 
@Katapippo

**Comment by Katapippo** [comment]
Thank you thank you
You are fantastic if you want you can see this [SHORTS ](https://youtube.com/shorts/hdGF-x0Wdfg?feature=share)how everything works perfectly, Thank you, Thank you

**Comment by RobinTail** [comment]
That's great, I'm super glad to read this. Thank you for recording this, @Katapippo 👍🏽
