### ISSUE TITLE
Feature: Auto ON after print

### ISSUE THREAD

**Issue by MelGrubb** [borisbu/OctoRelay#28]
I'd like my cooldown fan to turn on for X minutes when a print is completed. There is currently an option to turn relays OFF after a print, but no way to turn them ON.

**Comment by Sebbabas** [comment]
hello,
Yes this option would be useful for me too.

**Comment by mblacklin1** [comment]
Agreed - would love to see this implemented somehow.

**Comment by RobinTail** [comment]
I wanna change settings interface for this, providing a sort of matrix

| Event | Auto ON | Auto OFF |
|--------|:------:|:------:|
| Initially |☑️|  ☑️  |
| Before print | ☑️  | ☑️  |
| After print | ☑️  | ☑️  |

**Comment by RobinTail** [comment]
@MelGrubb @PalmyreSG1 @Sebbabas @mblacklin1 ,

The feature is available in the recently released version 3.4.0 🚀

**Comment by RobinTail** [comment]
>  fan to turn on for X minutes

The feature on turning something on for a limited time released in v3.8.0 🚀 
@MelGrubb
