### ISSUE TITLE
Doesn't work after update to 5.0

### ISSUE THREAD

**Issue by iduarte1966** [borisbu/OctoRelay#287]
After update to 5.0 I've lost the icons on dashboard, can't use this plugin anymore.
OctoPrint 1.10.2 Python 3.9.2 OctoPi* 1.0.0 (build 2023.10.09.151442

![image](https://github.com/user-attachments/assets/9fc236fa-8a6c-4a93-aac8-171de4c6a68b)
![image](https://github.com/user-attachments/assets/85383712-cfff-434c-b674-196ba3f3ae13)

**Comment by iduarte1966** [comment]
Solved.
Had to clear plugin data and setting each relay again.

![image](https://github.com/user-attachments/assets/81d4e889-d050-4ebb-aefc-e944de272d72)

**Comment by RobinTail** [comment]
Interesting.
Is there a chance that you still have logs for that case, @iduarte1966 ?

**Comment by RobinTail** [comment]
yes, @iduarte1966 
They are in this file:
![image](https://github.com/user-attachments/assets/de1256a2-8573-469a-aa5c-e12036095f0f)

**Comment by iduarte1966** [comment]
Seems that I don't have that "logging" menu
[image: image.png]
Ismael Duarte


Anna Bocharova ***@***.***> escreveu (sexta, 12/07/2024 à(s)
17:24):
