### ISSUE TITLE
Physical Button Plugin broken

### ISSUE THREAD

**Issue by ccle610** [borisbu/OctoRelay#299]
Plugin Version
5.0.1

Question
So far I have used "Physical Button"a GPIO Input via Hardware Button to toggle the light ( =>Action: GPIO toggle).

The output is also used by the Octorelay plug-in to control the light. This worked well for a long time. Unfortunately, the button no longer reacts as long as the Octo Relay plug-in is running. Without the Octorelay plug-in, everything works perfectly!
I also tried the Workaround with GCODE in Physical Button, but also this does not work.

Is this a topic for here, or for Physicl Button?

Additional context
Physical Button Version 0.6.2

**Comment by RobinTail** [comment]
yeah, I made a notice about it...

**Comment by RobinTail** [comment]
Here is the solution for that problem, @ccle610 : 

https://github.com/borisbu/OctoRelay/issues/263#issuecomment-2241546096

**Comment by ccle610** [comment]
Thx so much for this hint !

**Comment by ccle610** [comment]
Thx so much for this hint !

**Comment by RobinTail** [comment]
There is probably a way to bypass the lock (exclusive pin reservation) established by `gpiozero` with a single line, that I'm currently investigating here, trying to make a cleanest solution possible:
https://github.com/borisbu/OctoRelay/pull/315

**Comment by RobinTail** [comment]
Compatibility will be fixed in v5.1.0
