### ISSUE TITLE
Can not install new verion in Octoprint. 

### ISSUE THREAD

**Issue by cellfreak** [borisbu/OctoRelay#301]
ERROR: Package 'octorelay' requires a different Python: 3.7.3 not in '<4,>=3.9'

**Comment by RobinTail** [comment]
You've got the following options, @cellfreak :

- Upgrade your environment to have Python version at least 3.9
- Use OctoRelay version 4.x
  - available via the following link for manual installation:
  - `https://github.com/borisbu/OctoRelay/releases/download/4.2.1/release.zip`
