### ISSUE TITLE
Icons and relay controls do not appear when using Raspberry Pi 5.

### ISSUE THREAD

**Issue by corndog2000** [borisbu/OctoRelay#304]
I have two relays turned on in OctoPrint settings. I do not see any buttons in OctoPrint to control these relays.

OctoPrint installed on Raspberry Pi 5 using this script: [https://github.com/paukstelis/octoprint_deploy](https://github.com/paukstelis/octoprint_deploy)

OctoPrint verison: 1.10.2
OctoRelay Version: 5.0.2

Operating system version:
![image](https://github.com/user-attachments/assets/3e771258-cb56-407a-b471-d7702af75998)

Screenshots:
![image](https://github.com/user-attachments/assets/27ed6399-645f-41e0-8c0d-0864b919dfa9)
![image](https://github.com/user-attachments/assets/4a32232d-40ea-4af5-a0f2-068dca6bff8d)
![image](https://github.com/user-attachments/assets/5da1fd16-5b47-4750-ba59-1d3c1ea08ad2)

**Comment by corndog2000** [comment]
Octoprint log file:
[octoprint-logs.zip](https://github.com/user-attachments/files/16646920/octoprint-logs.zip)

**Comment by RobinTail** [comment]
There is an issue with your `lgpio` installation, @corndog2000 

```
2024-08-17 21:21:25,508 - py.warnings - WARNING - /home/pi/OctoPrint/lib/python3.11/site-packages/gpiozero/devices.py:300: PinFactoryFallback: Falling back from lgpio: [Errno 2] No such file or directory: '.lgd-nfy-3'
```

Therefore `gpiozero` is trying an alternative approach with `rgpio` but it's failing too

```
  File "/home/pi/OctoPrint/lib/python3.11/site-packages/gpiozero/pins/rpigpio.py", line 101, in __init__
    GPIO.setup(self._number, GPIO.IN, self.GPIO_PULL_UPS[self._pull])
RuntimeError: Cannot determine SOC peripheral base address
```

I'd suggest to make ensure `lgpio` python library to be installed properly.

```shell
pip3 install lgpio
```

That package should have been installed along with OctoRelay, but maybe there is an issue.
Try re-installing it manually, @corndog2000

**Comment by RobinTail** [comment]
I also find it suspicious that the images are broken on the page.

![image](https://github.com/user-attachments/assets/cc77eae5-eb6b-444b-8902-59c577f3b616)
 
Probably there is something wrong with the environment.
Consider a nightly build of [OctoPi](https://github.com/guysoft/OctoPi)

**Comment by RobinTail** [comment]
CC @ch3p4ll3

**Comment by ch3p4ll3** [comment]
Hi @corndog2000 what do u use to start octoprint? Systemd? In this case add `WorkingDirectory=/home/pi/OctoPrint` in the **Service** section of the octoprint unit file. Reload the services with `sudo systemct reload-daemons` and then try restarting octoprint with `sudo systemct restart octoprint`

**Comment by corndog2000** [comment]
After trying your suggestions I still have errors in the OctoPrint log. 

I already had lpgio installed it seems.

```bash
pi@rpi5:~/.PrusaMK4 $ pip3 install lgpio --break-system-packages
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: lgpio in /usr/lib/python3/dist-packages (0.2.2.0)
```

I have also added the WorkingDirectory to the OctoPrint systemd entry.

```bash
pi@rpi5:~/.PrusaMK4 $ cat /etc/systemd/system/PrusaMK4.service
[Unit]
Description=The snappy web interface for your 3D printer
After=network.online.target
Wants=network.online.target

[Service]
Environment="PORT=5001"
Environment="BASEDIR=/home/pi/.PrusaMK4"
Environment="CONFIGFILE=/home/pi/.PrusaMK4/config.yaml"
User=pi
ExecStart=/home/pi/OctoPrint/bin/octoprint serve --config=${CONFIGFILE} --basedir=${BASEDIR} --port=${PORT}
WorkingDirectory=/home/pi/.PrusaMK4

[Install]
WantedBy=multi-user.target
pi@rpi5:~/.PrusaMK4 $
```

Here is the new log file:
[octoprint.log](https://github.com/user-attachments/files/16649286/octoprint.log)

**Comment by ch3p4ll3** [comment]
Try changing GPIO, GPIO4 gave me problems too

**Comment by RobinTail** [comment]
I'm concerned about these two messages:

1. `Defaulting to user installation because normal site-packages is not writeable`
2. `2024-08-17 21:21:25,508 - py.warnings - WARNING - /home/pi/OctoPrint/lib/python3.11/site-packages/gpiozero/devices.py:300: PinFactoryFallback: Falling back from lgpio: [Errno 2] No such file or directory: '.lgd-nfy-3'`

I believe they are connected and related to some permission errors required for normal operation.

**Comment by corndog2000** [comment]
> Try changing GPIO, GPIO4 gave me problems too

GPIO 4 is only used on the Lights option. It has been disabled since I've installed OctoRelay. My two enabled relays are pins 13 and 26.

![image](https://github.com/user-attachments/assets/b6b1e09b-8fb4-430b-92cd-86a11e6f14ea)

**Comment by corndog2000** [comment]
> I'm concerned about these two messages:
> 
>     1. `Defaulting to user installation because normal site-packages is not writeable`
> 
>     2. `2024-08-17 21:21:25,508 - py.warnings - WARNING - /home/pi/OctoPrint/lib/python3.11/site-packages/gpiozero/devices.py:300: PinFactoryFallback: Falling back from lgpio: [Errno 2] No such file or directory: '.lgd-nfy-3'`
> 
> 
> I believe they are connected and related to some permission issues disrupting the normal operation.

That first message is due to this new message when using pip on Rasbian 12.

```bash
pi@rpi5:~/.PrusaMK4 $ pip3 install lgpio
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
pi@rpi5:~/.PrusaMK4 $
```

**Comment by corndog2000** [comment]
python3-lgpio is also already installed.

```bash
pi@rpi5:~/.PrusaMK4 $ sudo apt install python3-lgpio
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-lgpio is already the newest version (0.2.2-1~rpt1).
The following package was automatically installed and is no longer required:
  libcamera0.2
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@rpi5:~/.PrusaMK4 $
```

**Comment by ch3p4ll3** [comment]
> > Try changing GPIO, GPIO4 gave me problems too
> 
> GPIO 4 is only used on the Lights option. It has been disabled since I've installed OctoRelay. My two enabled relays are pins 13 and 26.
> 
> ![image](https://private-user-images.githubusercontent.com/7349261/358919091-b6b1e09b-8fb4-430b-92cd-86a11e6f14ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTkyMzQsIm5iZiI6MTcyMzk5ODkzNCwicGF0aCI6Ii83MzQ5MjYxLzM1ODkxOTA5MS1iNmIxZTA5Yi04ZmI0LTQzMGItOTJjZC04NmExMWU2ZjE0ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MThUMTYzNTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjRmMWZiMDZjMGU5NTJlYmFlNDYxMzY5OWI5ZThkMzIyMjI1OGY5MmVlZGZhOGRhNTA2YjljODAwOWNkNzI0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r137O3XrZ1HTCGJ-V4AqFKdTHebMAAxQg8yKqCLaZy8)

Ok, but I see that the light is still active. Try disable it or change the pin

**Comment by RobinTail** [comment]
Deactivate and restart OctoPrint, @corndog2000

**Comment by corndog2000** [comment]
I activated it just to show where GPIO 4 is being used. Like I said, it has been disabled the entire time I've been experiencing issues.

**Comment by ch3p4ll3** [comment]
Try stopping the service and starting it manually?

**Comment by ch3p4ll3** [comment]
> ```shell
> ExecStart=/home/pi/OctoPrint/bin/octoprint serve --config=${CONFIGFILE} --basedir=${BASEDIR} --port=${PORT}
> WorkingDirectory=/home/pi/.PrusaMK4
> ```

And also try changing the working directory to `/home/pi/OctoPrint`

**Comment by corndog2000** [comment]
I had to change the relays using GPIO 4, GPIO 7, and GPIO 8 to other GPIO numbers to get it working.

**Comment by RobinTail** [comment]
Interesting.
So it does work, but on other channels.
@ch3p4ll3 , do you know what's the reason behind it? Is there an existing issue at `gpiozero` about that problem?

**Comment by ch3p4ll3** [comment]
> Interesting. So it does work, but on other channels. @ch3p4ll3 , do you know what's the reason behind it? Is there an existing issue at `gpiozero` about that problem? Or is it the board issue?

![image](https://github.com/user-attachments/assets/670e2f5b-755a-43c0-a297-7ea57993076a)
maybe 'cause GPIOs 4/7/8 have other purposes beyond being an IO?

**Comment by ch3p4ll3** [comment]
@corndog2000 Do you have 1-Wire enabled? https://forums.raspberrypi.com/viewtopic.php?t=370952

**Comment by RobinTail** [comment]
> maybe 'cause GPIOs 4/7/8 have other purposes beyond being an IO?

Could be. And those purposes selected by what or how?
is it configurable in `raspi-config`?

**Comment by corndog2000** [comment]
> > maybe 'cause GPIOs 4/7/8 have other purposes beyond being an IO?
> 
> Could be. And those purposes selected by what or how?
> is it configurable in `raspi-config`?
> 
> At least `1-Wire` is there
> ![image](https://github.com/user-attachments/assets/95b8648f-7f34-41f0-bcca-2182eed41653)
> 

Pins 7 and 8 are used in the SPI bus which is also there in raspi-config.

**Comment by RobinTail** [comment]
Ok, then I believe we figured this out.
@ch3p4ll3 , thank you for the support.
