### ISSUE TITLE
Not possible to update to the latest version

### ISSUE THREAD

**Issue by MarkusAndreasMueller** [borisbu/OctoRelay#313]
Thanks for the great plugin and the maintenance!

Apparently Octopi for Octoprint is still supported with an older python version than the one needed for the OctoRelay. 

Is it possible to downgrade the dependency? 

Here is the error code:  
++++++++++++++++++++++++++++++++
Aktualisiere OctoRelay auf 5.0.2
++++++++++++++++++++++++++++++++
/home/pi/oprint/bin/python3 -m pip --disable-pip-version-check install https://github.com/borisbu/OctoRelay/releases/download/5.0.2/release.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/borisbu/OctoRelay/releases/download/5.0.2/release.zip
Downloading https://github.com/borisbu/OctoRelay/releases/download/5.0.2/release.zip (51 kB)
Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python3.7/site-packages (from OctoRelay==5.0.2) (1.10.2)
Requirement already satisfied: gpiozero in /home/pi/oprint/lib/python3.7/site-packages (from OctoRelay==5.0.2) (1.6.2)
Requirement already satisfied: RPi.GPIO in /home/pi/oprint/lib/python3.7/site-packages (from OctoRelay==5.0.2) (0.7.0)
ERROR: Package 'octorelay' requires a different Python: 3.7.3 not in '<4,>=3.9'

Die Aktualisierung wurde nicht erfolgreich abgeschlossen. Bitte konsultiere <code>octoprint.log</code> und <code>plugin_softwareupdate_console.log</code> für Details.

**Comment by RobinTail** [comment]
Hello, @MarkusAndreasMueller 
Version 5 of OctoRelay requires Python 3.9 or higher.
You're having Python 3.7.3.
Your version of Python is supported by OctoRelay v4, that you can install using this link in your plugin manager:

```
https://github.com/borisbu/OctoRelay/releases/download/4.2.1/release.zip
```

It is as good and functional as the v5.
