### ISSUE TITLE
ciao

### ISSUE THREAD

**Issue by JirkaAndrle** [borisbu/OctoRelay#42]
Hi chi ask I have a raspberry pi 4 b and I can easily connect a 5v relay or just 3.3v on a pini respberry won't load if I add a relay?

**Comment by JirkaAndrle** [comment]
He will not be burdened

**Comment by ThreeGs1969** [comment]
I tried to use a 5v relay as well and it would not work. Then I found this video of how to mod a 5v relay to work on the GPIO trigger. I have the parts on order so I am hopeful this will work as the relay in the video is the exact one I have.
https://youtu.be/p7wmzAzDX-Q

**Comment by RobinTail** [comment]
This question seems to be resolved. In case it's not — create another one.
