### ISSUE TITLE
Feature: @command support

### ISSUE THREAD

**Issue by jneilliii** [borisbu/OctoRelay#43]
It came up today on the Discord server that having @ command support in the plugin may be beneficial for users of OctoDash. I'm going to look into submitting a PR for this feature, but will require a little refactor I think since all the work is currently happening in the SimpleApiPlugin mixin implementation. Will break out the actual working bits of the function to another function that can be called by the API, which would then also allow for integrating the @ command support.

**Comment by RobinTail** [comment]
Documentation: https://docs.octoprint.org/en/master/features/atcommands.html
