### ISSUE TITLE
Resets when print starts

### ISSUE THREAD

**Issue by GordonMKF** [borisbu/OctoRelay#46]
Setup relay to switch printer off and on. Works fine until print loaded and starts then printer is shutoff.
Setup a relay on a second Pi with another printer but only controlling a light and same situation. On print start light switches off. Print continues and I can switch the light on without any issues.

![image](https://user-images.githubusercontent.com/17933476/146827643-97903181-2718-4dca-a851-317a60874035.png)

Printer on/off relay is externally powered so only signal triggering. Light relay on second Pi is powered from Pi.
Raspi 3B+'s with all updates done.

**Comment by Ruggero1912** [comment]
Same here

**Comment by mArJaNu-yV** [comment]
Same situation. orctoprint 1.7.3.

**Comment by NDR008** [comment]
I got the same issue... :/

**Comment by borisbu** [comment]
For my relay board, I need to invert the output. Did you try to do that?

![image](https://user-images.githubusercontent.com/10959304/153159095-d976187f-7b97-4798-9956-c2fee5e843db.png)

**Comment by NDR008** [comment]
@borisbu I am using a different module that was design for the ESP D1 mini.
But basically your program is working for turning on / off when I click the icon.
It just turns off when I click print.

Question - is the GPIO being used in pull-down or pull-up? Are you setting the internal resistor?

**Comment by NDR008** [comment]
@borisbu I understood what you mean... if you use the relay the opposite way, drive the relay to keep the printer off, the bug does not occur... but there must be a reason for this.
Let me try to poke at the code myself :)

**Comment by NDR008** [comment]
@borisbu Update again: If I edit this line:
https://github.com/borisbu/OctoRelay/blob/5a940f5fa253930341db3ae0e864bb691fb39a5e/octoprint_octorelay/__init__.py#L320
From
GPIO.output(relay_pin, inverted != True)

to
GPIO.output(relay_pin, inverted == True)
The relay works as expected without Inverted settings
So somewhere here something is bizarre...

**Comment by NDR008** [comment]
I made a pull request that should fix it.

**Comment by Diaprojector** [comment]
Hi, I've had this issue as well (came here to report it). Seems like this issue is only on the GPIO23 pin. Changed it to GPIO17 and had no issues.

**Comment by jshep321** [comment]
Hi,
A fresh install of octoprint on a new pi4 using a powerswitch tail relay (https://www.adafruit.com/product/268).  GPIO18 and gnd connected to the relay.  OctoRelay works perfectly until I actually start a print, then clicks off.  Non-inverted mode.

I moved over to the PSU Control plugin, (which uses the deprecated GPIO library I believe) and it works fine.

**Comment by zlomennypez** [comment]
This error has the source in printer icon settings. If you set the printer relay to light, it works normally.

**Comment by jamesturner-mark43** [comment]
> @borisbu Update again: If I edit this line:
> 
> https://github.com/borisbu/OctoRelay/blob/5a940f5fa253930341db3ae0e864bb691fb39a5e/octoprint_octorelay/__init__.py#L320
> 
> 
> From
> GPIO.output(relay_pin, inverted != True)
> to GPIO.output(relay_pin, inverted == True) The relay works as expected without Inverted settings So somewhere here something is bizarre...

Can confirm that this fix worked for me.

**Comment by hcooper** [comment]
I'm going to suggest this is related to what I fix in https://github.com/borisbu/OctoRelay/pull/55 - the inactive relay configs are being processes like they're active, and one of the default configs conflicts with the relay you've setup.

See my suggested quick fixes here:
 - https://github.com/borisbu/OctoRelay/issues/39#issuecomment-1329686757
 - https://github.com/borisbu/OctoRelay/issues/52#issuecomment-1329695190

**Comment by RobinTail** [comment]
🚀  The issue most likely fixed in 2.0.1.
In case it's not, please create another one, @GordonMKF
