### ISSUE TITLE
Relays with time program

### ISSUE THREAD

**Issue by quantenquark** [borisbu/OctoRelay#61]
Hi, 
I am using the plugin which is working perfectly. Thanks a lot for your work!

Would it be feasable to implement a time program for one channel as an additional feature to allow intermittent switching operations?

Best
Achim

**Comment by RobinTail** [comment]
Hello @quantenquark 

Please provide an example of such a time program and switching operation.

**Comment by quantenquark** [comment]
Hi Robin, I could imagine a kind of timer to keep e.g. fans or an exhaust system in operation for another 5 minutes after printing.

Regards
Achim

**Comment by RobinTail** [comment]
> Hi Robin, I could imagine a kind of timer to keep e.g. fans or an exhaust system in operation for another 5 minutes after printing.


Hello @quantenquark ,

The plugin already has these two settings for each relay:

- OFF after printing	— Turns the relay OFF after finished printing
- Delay	— Postpones turning the relay OFF for X seconds

Would they be enough to achieve the desired behavior you mentioned?

Otherwise what is missing?

**Comment by RobinTail** [comment]
Or you meant that you want to turn ON something after print and after some time turn it OFF?

**Comment by quantenquark** [comment]
Definitly off but selecting the state World also ve a benefit.

**Comment by RobinTail** [comment]
> I could imagine a kind of timer to keep e.g. fans or an exhaust system in operation for another 5 minutes after printing.

Implemented by #166 , released yesterday in v3.8.0 🚀 , @quantenquark
