### ISSUE TITLE
Is this plugin abandoned?

### ISSUE THREAD

**Issue by hcooper** [borisbu/OctoRelay#63]
For octoprint house keeping purposes please confirm if this plug is abandoned.

If so (or in the case of a few weeks of silence) I'll update the octoprint repository and advertise for a new maintainer.

Thanks.

**Comment by boris-swiftmind** [comment]
Hi, I currently don't have the time to maintain the plugin, if you can find someone to keep it alive, I'm more than happy.

**Comment by RobinTail** [comment]
@borisbu , could you please send me the invitation again?

**Comment by RobinTail** [comment]
the plugin is not abandoned, @hcooper .
Please help me to complete https://github.com/borisbu/OctoRelay/pull/55
