### ISSUE TITLE
Possible XSS

### ISSUE THREAD

**Issue by gigibu5** [borisbu/OctoRelay#8]
Hi, 
I viewed your plugin, a lot better than mine :sweat_smile:. Nice job. I only saw a single flaw, for your "icons" you use a text field in the settings, that's nice, because you can set any icon you want, but there is a catch. You can run any html, including scripts, which you absolutely do not want! It's probably not that big of a deal, because most users use this at home, but if you're printer is used by other users, you do not trust completely, it would be wise to fix this issue. 

Fix recomendation:
Escape every < and > character with replace method on string.
```py
string = string.replace("<", "&lt;")
string = string.replace(">", "&gt;")
```

Edit:
The same thing is with the name option in the settings.

**Comment by borisbu** [comment]
Hi, thanks for the OctoLight plugin, it gave me a good start into making OctoPrint plugins. I am fully aware of this, but want to allow the user  to add html tags, and also for example displaying images with a public url.
I guess if people want to have a XSS free version, they have to fork and xml escape the html output.
