### ISSUE TITLE
Navbar Hover Cursor wrong

### ISSUE THREAD

**Issue by Bra1nK** [borisbu/OctoRelay#9]
When hovering over the 'Light' the cursor is a text one, when hovering over the 'Printer' it's an arrow, would be better if they were both the usual 'Pointing Finger'

**Comment by borisbu** [comment]
done

**Comment by Bra1nK** [comment]
Excellent, when will there be a new commit ?

**Comment by borisbu** [comment]
it's in here: https://github.com/borisbu/OctoRelay/commit/f0aa70d827ccf7c3aa877f48ab7d5d5b0228d095
